### ISSUE TITLE
abs (V2 x y) is not defined correctly

### ISSUE THREAD

**Issue by SwiftsNamesake** [ekmett/linear#113]
Maybe I'm missing something, but I thought the mathematical definition of `abs v` was defined as the distance between `v` and the origin.

If you take a peek at the [`Num` instance of `V2`](https://github.com/ekmett/linear/blob/master/src/Linear/V2.hs#L166), you'll instead find that the absolute value is defined as the absolute of each component individually (`fmap abs`).

Is that the intended behaviour or simply a mistake?

**Comment by SwiftsNamesake** [comment]
I suppose a proper definition would require a `Floating` constraint on the type parameter.

**Comment by Taneb** [comment]
The reason for this definition, as you worked out, is that it would require a `Floating` constraint, stopping us from effectively using, for example, `V2 Integer`.

The `abs` function you describe is provided in the `Metric` class in `Linear.Metric` as `norm`. Alternatively, you could use `Complex` in `Data.Complex` in `base` which has `abs` defined in the way you describe, but then you lose out on a lot of the functionality provided by `linear`.

**Comment by SwiftsNamesake** [comment]
It just goes to show - once again - that we need a better Num class. I ran into the same issue while defining my own vector type class.

As an aside, do you happen to know whether this fact is documented anywhere? I couldn't find any mention of it on Hoogle.

**Comment by ocharles** [comment]
`V2 Integer` doesn't even make mathematical sense anyway. A vector space is defined over a field, and `Integer` is not a field (it doesn't have multiplicative inverses).

**Comment by Asmageddon** [comment]
I would argue that even if it might not make perfect mathematical sense, it's still a very useful construct, and the decision to exclude it like this seems quite arbitrary and unnecessary.

**Comment by SwiftsNamesake** [comment]
Either way, don't you think the decision - and its rationale - should be documented somewhere?

**Comment by ekmett** [comment]
@ocharles: V2 can be used for modules over rings not just for vector spaces. I very commonly instantiate it at types that don't have inverses.

`abs` is one of those glaring historical mistakes in the language design. The _only_ thing we can do is implement it pointwise.  We have to implement it in order to implement `Num`, so it does the only thing it can do consistent with the piddly laws we're offered for `abs`, which is that `abs x * signum x = x`.

It notably can't compute a scalar from a vector. The types do not match! Yet, `abs :: Num a => a -> a`. 

This is why there are tools in here to compute `quadrance` and `norm`. `quadrance` is `norm^2` and is always defined even for `V2 Integer`. `norm` is what you expect of `abs` but can exist. This covers all of the usecases and is mathematically correct.

I have no objection to better documentation. I just don't know particularly where it should go.

**Comment by SwiftsNamesake** [comment]
What do you think of the efforts to rehaul the Prelude (and `base`)? I'm thinking of [Foundation](https://github.com/haskell-foundation/foundation) and `classy-prelude` in particular. Seems like a worthy pursuit to me. Just curious what you think, I'm obviously not suggesting that we deprecate Prelude.

As for the docs, doesn't Hoogle support commenting class instances? Either that, or at the top of each affected module, with a reference to the functions you mentioned.

**Comment by ekmett** [comment]
I'm personally not a big fan of the current alternate Prelude offerings. As for refactoring the numeric hierarchy, it definitely requires extending the language beyond Haskell 98. Even just this `abs` example needs type families or functional dependencies. Without a language standard _that can be implemented by another compiler_ that includes enough to govern that functionality, it would be a bad idea to redesign `base` around such functionality. This is why I've not been in a hurry to push forward any major changes in the `Num` hierarchy through the CLC.  Until `haskell-prime` can describe type families, most such changes would be at best incremental, and satisfy nobody. You'd have a huge amount of work for gains that aren't enough to satisfy the crowd that wants a more rigorous numeric tower.

Re: `Foundation` and `classy-prelude`, they no such need for portability / standardizability, which opens their horizons a bit. But my experience with `classy-prelude` is by designing for things that both create and consume with the same typeclass you wind up with the antipattern of needing `asHashMap` and the like to resolve type ambiguities. I rather prefer being able to structure my code without such type-directing crutches, and I find `MonoTraversable` and the like never suits my needs. YMMV, but I have no interest in moving it into `Prelude`.

As for class instance documentation: Hoogle does support documenting class instances, but the formatting is awful. You just get a blurb off to the right of the instance.

**Comment by SwiftsNamesake** [comment]
Do you contribute to Hoogle at all? Seems like you're everywhere. Maybe we could suggest an enhancement.

Anyhow, would you object to my second suggestion, then (ie. mention it at the top of each module)? It's not ideal, but it'd work and people would see it.

**Comment by acowley** [comment]
The type of `abs` being what it is makes this not a `linear` matter, in my opinion. There is already a commonly used `abs`, it does not have an appropriate type for vector norm, so it can not be the vector norm. Adding a few words to the `Num` instances sounds reasonable, but this is a universal problem with Haskell, so publicizing that more generally might be more helpful to future newcomers to ensure they approach all `Num` instances with their shields raised.

**Comment by SwiftsNamesake** [comment]
Fair enough. Where would you do the publicizing though?

**Comment by acowley** [comment]
That's the sticky bit :/ Writing blog posts that call out this limitation incidental to whatever interesting thing you're writing about always helps. More generally, agitating for a new language standard as Ed suggests is the right long-term move.

I'm more positive on the potential of alternate preludes since they face different obstacles than producing a useful new language standard. Integrating a port of `linear` with `Foundation` would probably be a valuable exercise, but I don't see how we can avoid fragmenting things.

Calling out this issue periodically as done here is actually pretty helpful as it reminds us all of this little wart that we otherwise start taking for granted.

**Comment by ekmett** [comment]
I don't currently contribute to Hoogle. I try to stick to things that should exist for some deep fundamental mathematical reason -- or which I personally find entertaining -- and Hoogle is a squishy thing formed of opinions. =)

**Comment by SwiftsNamesake** [comment]
Alright, I might just delve into the slurry of opinions myself then. Deep
breath (also, not to self, Ed Kmett approves of emojis).

lör 17 sep. 2016 kl. 17:31 skrev Edward Kmett <notifications@github.com>:

**Comment by ekmett** [comment]
:+1:
